sonar.projectKey=edgar-data-fetcher
sonar.projectName=edgar-data-fetcher

sonar.sources=setup.py
sonar.tests=tests
sonar.test.inclusions=tests/**

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml
